lwm2m e2e with no securityMode
Edgenesis/shifu pull request #1018
Opened 2024-10-17 10:50 UTC by beingStrongeryqqq

**What this PR does / why we need it**:
Test lwm2m e2e with no securityMode
**Will this PR make the community happier**? 
yes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [x] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-10-18 09:20 UTC, tomqin93 requested changes
@beingStrongeryqqq added some comments, please take a look

2024-10-18 09:20 UTC, tomqin93 commented on azure-pipelines/azure-pipelines.yml
> +              make buildx-push-image-deviceshifu-http-lwm2m
use build instead of push for e2e

2024-10-18 09:20 UTC, tomqin93 commented on examples/deviceshifu/demo_device/edgedevice-lwm2m/mockdevice/lwm2m-mock.yaml
> +        image: edgenesis/lwm2m-demo-leshan-client:nightly
we need to either include this image in the dockerfile directory, add it into makefile or use the official leshan-client

2024-10-18 09:20 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwm2m/checkoutput.sh
> +# Retrieve LwM2M server information and attempt multiple retries
and attempt => with

2024-10-18 09:20 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwm2m/checkoutput.sh
Since this is a new test, can we use python instead?

2024-10-21 04:53 UTC, beingStrongeryqqq commented on examples/deviceshifu/mockdevice/lwm2m/checkoutput.sh
🆗

2024-10-22 05:58 UTC, rhoninl commented on examples/deviceshifu/demo_device/edgedevice-lwm2m/lwm2m/lwm2m-deviceshifu-configmap.yaml
> +    serverUrl: coap://leshan-service.deviceshifu.svc.cluster.local:5683
what's this

2024-10-22 05:58 UTC, rhoninl commented on examples/deviceshifu/demo_device/edgedevice-lwm2m/lwm2m/lwm2m-deviceshifu-configmap.yaml
> +
remove empty line

2024-10-22 05:59 UTC, rhoninl commented on examples/deviceshifu/demo_device/edgedevice-lwm2m/mockdevice/lwm2m-mock.yaml
> +            cpu: "500m"
remove resource limit

2024-10-22 07:48 UTC, closed without merging