Lwm2m with security
Edgenesis/shifu pull request #1023
Opened 2024-10-22 08:30 UTC by beingStrongeryqqq

**What this PR does / why we need it**:
lwM2M e2e test with security.
**Will this PR make the community happier**? 
yes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [x] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2024-10-23 10:19 UTC, rhoninl commented on examples/deviceshifu/mockdevice/lwM2M/checkoutput.sh
> +#!/bin/bash
remove if not used

2024-10-23 10:36 UTC, tomqin93 approved these changes

2024-10-25 01:12 UTC, tomqin93 requested changes
@beingStrongeryqqq added some comments, the rest looks good

2024-10-25 01:12 UTC, tomqin93 commented on azure-pipelines/azure-pipelines.yml
> +      - job: kind_e2e_test_socket
Let's switch the test order of socket and lwm2m test for better readability

2024-10-25 01:12 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwM2M/checkoutput.sh
> +service_name=$(kubectl get services -n deviceshifu -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}')
you should use `-l app=deviceshifu-lwm2m-deployment` to select the service

2024-10-25 01:12 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwM2M/checkoutput.sh
> +    if [[ $out != "Error on reading object" && -n "$out" ]]; then
check `-n "$out"` first

2024-10-25 01:12 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwM2M/checkoutput.sh
> +    echo "Device is unhealthy. Attempting to reconnect... ($i/10)"
revert to 5

2024-10-25 01:12 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwM2M/checkoutput.sh
> +    echo "Device is still unhealthy after 10 attempts. Exiting..."
ditto

2024-10-25 01:12 UTC, tomqin93 commented on examples/deviceshifu/mockdevice/lwM2M/checkoutput.sh
> +if [[ $out == "Error on reading object" || -z "$out" ]]; then
ditto

2024-10-25 10:42 UTC, tomqin93 approved these changes
LGTM

2024-10-28 02:19 UTC, rhoninl commented on azure-pipelines/azure-pipelines.yml
> +            displayName: "Shifu demo device lwM2M E2E test without security"
with security

2024-10-28 02:26 UTC, rhoninl approved these changes
LGTM

2024-10-28 04:47 UTC, merged