implement socket encoding and bufferlength
Edgenesis/shifu pull request #268
Opened 2022-09-23 08:27 UTC by MrLeea-13155bc

**What this PR does / why we need it**:
implement socket encoding and bufferlength
**Will this PR make the community happier**? 
yes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2022-09-23 08:29 UTC, BtXin requested changes
Please fill `How is this PR tested` section

2022-09-25 08:17 UTC, tomqin93 requested changes
@MrLeea-13155bc added some comment, please take a look

2022-09-25 08:17 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket.go
> +			klog.Errorf("Error when encode message with Encoding, %v", err)
let's print out the `Encoding` as well

2022-09-25 08:17 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket.go
> +			http.Error(w, "Failed to encode message with Encoding, error: "+err.Error(), http.StatusBadRequest)
same as above

2022-09-25 08:17 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket.go
> +func praseCommandWithEncode(input string, encode string) ([]byte, error) {
are we decoding the command in this function? if so change the function name accordingly

2022-09-25 08:17 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket_test.go
> +		t.Errorf("%+v", err)
Let's print out the error context in addition to the error itself, same for other errors in test

2022-09-25 08:17 UTC, tomqin93 commented on pkg/k8s/api/v1alpha1/edgedevice_types.go
> +	BufferLength *int    `json:"bufferLength,omitempty"`
Can you please look into CRD default values? we should be able to set default values here directly 
https://book.kubebuilder.io/reference/markers/crd-validation.html

2022-09-26 06:24 UTC, tomqin93 requested changes
@MrLeea-13155bc added some comments

2022-09-26 06:24 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket.go
> +
remove extra newline

2022-09-26 06:24 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocketconfig.go
> +	EncodeHexStr  = "hex"
let's put encoding/decoding support inside `EdgeDevice` definition since it belongs to CRD configuration

2022-09-26 07:18 UTC, tomqin93 reviewed
@MrLeea-13155bc added some comment

2022-09-26 07:18 UTC, tomqin93 commented on pkg/k8s/api/v1alpha1/edgedevice_types.go
> +	Encoding *string `json:"encoding,omitempty"`
let's use `Encoding *Encoding...` for type

2022-09-26 07:18 UTC, tomqin93 commented on pkg/k8s/api/v1alpha1/edgedevice_types.go
> +)
we can define `type Encoding` with the following constants:
```go
Encoding UTF8 = "utf-8"
Encoding Hex = "hex"
```

2022-09-27 01:41 UTC, tomqin93 reviewed
@MrLeea-13155bc added comments on 1 issue, the rest looks good

2022-09-27 01:41 UTC, tomqin93 commented on pkg/k8s/crd/config/manager/kustomization.yaml
> +  newTag: v0.0.1
should we revert this?

2022-09-27 01:41 UTC, tomqin93 commented on pkg/k8s/crd/install/config_default.yaml
> +        image: edgehub/shifu-controller:v0.0.1
see comment above

2022-09-27 01:41 UTC, tomqin93 commented on pkg/k8s/crd/install/shifu_install.yml
> +        image: edgehub/shifu-controller:v0.0.1
see comment above

2022-09-27 01:51 UTC, tomqin93 approved these changes
LGTM

2022-09-27 02:21 UTC, BtXin submitted a review, later dismissed
LGTM

2022-09-27 02:53 UTC, kris21he commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket.go
>  			http.Error(w, "Failed to send message to socket, error: "+err.Error(), http.StatusBadRequest)
should this a bad request error or an server internal error?

2022-09-27 02:53 UTC, kris21he commented on pkg/deviceshifu/deviceshifusocket/deviceshifusocket.go
> +			http.Error(w, "Failed to Read data from connection to buffer, for Read 0 byte from buffer", http.StatusBadRequest)
ditto

2022-09-28 05:19 UTC, tomqin93 approved these changes

2022-09-28 05:19 UTC, merged