Update README.md
Edgenesis/shifu pull request #294
Opened 2022-10-09 01:32 UTC by rachelzhang0922

updated the introducion based on discussion

2022-10-09 07:32 UTC, tomqin93 reviewed
@rachelzhang0922 added 2 comments

2022-10-09 07:32 UTC, tomqin93 commented on README.md
> +- ***Shifu*** is a Kubernetes native framework that achieves aerospace-grade stability (up to 99.9999%).
should we reference `https://kubernetes.io` for `Kubernetes`?
`aerospace-grade` => `aerospace grade`

2022-10-09 07:32 UTC, tomqin93 commented on README.md
> +- Device protocols and drivers are compiled as configuration files, which are efficient and reusable.
... from configuration files,...

2022-10-09 07:34 UTC, BtXin commented on README.md
> +***Shifu*** is a native framework to help IoT developers interact with physical devices. ***Shifu*** virtualizes the management and monitoring of devices, giving them the ability to run automatically
`native` => `kubernetes native` 
Native in computer science usually means it is written in C/C++

2022-10-10 02:32 UTC, BtXin commented
I heard that we are trying to avoid using the word `kubernetes` in readme. In that case you can change `kubernetes native` to `cloud native`.

2022-10-11 03:05 UTC, BtXin commented on README.md
> +- Modular deployment of devices, developers can simply load them on demand.
Modularized deployment

2022-10-12 10:33 UTC, saiyan86 requested changes

2022-10-12 10:33 UTC, saiyan86 commented
why not reuse the highlights on https://shifu.run/ ?

2022-10-13 02:15 UTC, rachelzhang0922 commented on README.md
> +- Device protocols and drivers are compiled from configuration files, which are efficient and reusable.
should we add it as the third item or replace the whole context?

2022-10-26 08:17 UTC, closed without merging