new readme
Edgenesis/shifu pull request #352
Opened 2022-10-26 08:23 UTC by rachelzhang0922

**What this PR does / why we need it**:

**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2022-10-26 08:31 UTC, saiyan86 submitted a review, later dismissed

2022-10-26 09:01 UTC, BtXin commented on README.md
> +***Shifu*** is the next-generation open source IoT development framework, making developing an IoT app as simple as developing a Web app. The high extensibility of ***Shifu*** allows it to integrate
`making developing an IoT app as simple as developing a Web app` - > `makes developing an IoT app as simple as developing a Web app`
`Once integrating a device` -> `Once a device is integrated`

2022-10-26 09:03 UTC, BtXin commented on README.md
> +Shifu can always be deployed with a single command.
~~always~~

2022-10-26 09:07 UTC, BtXin commented on README.md
> +Shifu should automatically recognize and provide basic functionalities to a supported IoT device. Once the developer completes Shifu's template, all features of the device should be immediately avail
`Shifu should automatically recognize and provide basic functionalities to a supported IoT device` -> `Shifu will automatically recognize and provide basic functionalities to a supported IoT device`

2022-10-26 09:08 UTC, BtXin commented on README.md
> +Developer can further implement Shifu's interface/SDKs to create custom features and unleash endless possibilities.
~~SDKS~~
we don't have sdks right now.

2022-10-26 09:11 UTC, saiyan86 commented on README-zh.md
> +|🛡️安全|联合国的云原生安全团队操刀，无论是数据加密还是网络安全，Shifu不一而足。|
|🛡️安全|联合国的云原生安全团队操刀，无论是数据加密还是网络安全，Shifu均可无缝集成。|

2022-10-26 09:12 UTC, saiyan86 commented on README-zh.md
> +开发者可以进一步实现Shifu的接口/SDK，以创建自定义功能，释放出无限的可能性。
马上就有了，我有一个PR在加shifuctl

2022-10-26 09:12 UTC, BtXin commented on README-zh.md
> +开发者可以进一步实现Shifu的接口/SDK，以创建自定义功能，释放出无限的可能性。
> 马上就有了，我有一个PR在加shifuctl

ok

2022-10-26 09:14 UTC, BtXin commented on README-zh.md
> +|🛡️安全|联合国的云原生安全团队操刀，无论是数据加密还是网络安全，Shifu不一而足。|
我在想是`前联合国的云原生安全团队`还是`联合国的前云原生安全团队`哪个比较好

2022-10-26 09:53 UTC, rachelzhang0922 commented on README-zh.md
> +|🛡️安全|联合国的云原生安全团队操刀，无论是数据加密还是网络安全，Shifu不一而足。|
联合国前团队，不然语义有问题了

2022-10-27 11:45 UTC, tomqin93 requested changes
@rachelzhang0922 added some comment, please take a look

2022-10-27 11:45 UTC, tomqin93 commented on README.md
> +***Shifu*** is the next-generation open source IoT development framework, makes developing an IoT app as simple as developing a Web app. The high extensibility of ***Shifu*** allows it to integrate a
reduced to => simplified to

2022-10-27 11:45 UTC, tomqin93 commented on README.md
> +|💻 Ultra-fast|From thermohydrometers using standard protocols to complex machinery using proprietary drivers, Shifu is capable of integrating all kinds of heterogeneous devices.|
Blazingly fast

2022-10-27 11:45 UTC, tomqin93 commented on README.md
> +#### 🪄Easy to extend
Extensibility ?

2022-10-27 11:45 UTC, tomqin93 commented on README.md
> +Shifu aims to achieve zero maintenance by adopting cutting-edge cloud native best practices. After all, Shifu should take care of himself and make operators' lives easier!
opeartors => DevOps

2022-10-28 08:05 UTC, tomqin93 reviewed
@rachelzhang0922 added 2 comment, the rest looks good

2022-10-28 08:05 UTC, tomqin93 commented on README.md
> +|🌐 Global Community|Benefiting from its Kubernetes' native architecture, Shifu can seamless integrate with the powerful cloud native software eco-system that allows developers around the world to hel
Let's be consistent with the Emojis for both versions

2022-10-28 08:05 UTC, tomqin93 commented on README.md
> +***Shifu*** is the next-generation open source IoT development framework, makes developing an IoT app as simple as developing a Web app. The high extensibility of ***Shifu*** allows it to integrate a
simplified to simple web development => simplified to web development

2022-10-28 08:41 UTC, tomqin93 approved these changes
LGTM

2022-10-28 08:44 UTC, saiyan86 approved these changes

2022-10-28 08:44 UTC, merged

2022-10-28 08:44 UTC, saiyan86 commented
LGTM