feat: update ignore
Edgenesis/shifu pull request #357
Opened 2022-10-31 02:12 UTC by 180909

**What this PR does / why we need it**:

**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2022-10-31 05:23 UTC, saiyan86 requested changes

2022-10-31 05:23 UTC, saiyan86 commented on .gitignore
>  setup-envtest
blank line

2022-10-31 05:23 UTC, saiyan86 commented on .gitignore
> +*.exe~
what does `~` mean?

2022-11-09 04:36 UTC, tomqin93 submitted a review, later dismissed

2022-11-09 04:38 UTC, tomqin93 approved these changes

2022-11-09 04:39 UTC, merged