<bugFix>Fix telemetry service path
Edgenesis/shifu pull request #364
Opened 2022-11-02 02:29 UTC by MrLeea-13155bc

**What this PR does / why we need it**:
Fix Telemetry Service need set handler manually
**Will this PR make the community happier**? 
yes
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [x] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2022-11-02 03:54 UTC, tomqin93 requested changes
@MrLeea-13155bc added some comments, please take a look

2022-11-02 03:54 UTC, tomqin93 commented on examples/mqttTelemetryService/telemetryservices.py
> +from flask import Flask, request, make_response
rename to mock device

2022-11-02 03:54 UTC, tomqin93 commented on examples/tdengineTelemetryService/telemetryservices.py
> +from flask import Flask, request, make_response
rename to mock device

2022-11-02 03:54 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifubase/pushtelemetry.go
> +		telemetryServicePath := *tss.TelemetrySeriveEndpoint + `/mqtt`
use type/const instead of literal strings

2022-11-02 03:54 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifubase/pushtelemetry.go
> +		telemetryServicePath := *tss.TelemetrySeriveEndpoint + `/sql`
ditto

2022-11-02 09:03 UTC, tomqin93 reviewed
@MrLeea-13155bc added some comment

2022-11-02 09:03 UTC, tomqin93 commented on examples/mqttTelemetryService/deployment/http-deviceshifu-telemetryservice.yaml
> +--- #telemetry_service.yaml
we can remove this line since this YAML only contains one config

2022-11-02 09:03 UTC, tomqin93 commented on examples/tdengineTelemetryService/deployment/http-deviceshifu-telemetryservice.yaml
> +--- #telemetry_service.yaml
ditto

2022-11-02 09:04 UTC, MrLeea-13155bc commented on pkg/telemetryservice/install/telemetryservice_install.yaml
> +apiVersion: apps/v1
maybe

2022-11-03 06:14 UTC, tomqin93 reviewed
@MrLeea-13155bc added 1 typo comment, the rest looks good

2022-11-03 06:14 UTC, tomqin93 commented on examples/httpDeviceShifu/deployment/http-deviceshifu-telemetryservice.yaml
> +      dbtype: TDEngine
e should be lower case

2022-11-03 10:46 UTC, tomqin93 approved these changes
LGTM

2022-11-04 06:04 UTC, merged