Instruction phton func name
Edgenesis/shifu pull request #369
Opened 2022-11-02 11:45 UTC by Twpeak

**What this PR does / why we need it**:

**Will this PR make the community happier**? 
Solved Unable to use customize deviceshifu #338
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2022-11-09 01:53 UTC, tomqin93 requested changes
@Twpeak added 1 comment, please take a look
Also, please update the how-to guide for customized deviceShifu

2022-11-09 01:53 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifuhttp/deviceshifuhttp.go
> +			InstructionFuncName, shouldUsePythonCustomProcessing := deviceshifubase.CustomInstructionsPython[handlerInstruction]
let's not use capitalized `I` for variable names that are not being exported, same for other occurrences.

2022-12-12 02:58 UTC, tomqin93 submitted a review, later dismissed

2022-12-12 03:43 UTC, kris21he reviewed
LGTM

2022-12-21 05:12 UTC, kris21he commented
@Twpeak this PR has too much commits and the change seems not correct, can we close this and init another one that have the clean changes?

2022-12-26 05:42 UTC, kris21he approved these changes

2022-12-26 05:44 UTC, merged