Newest readme
Edgenesis/shifu pull request #455
Opened 2023-01-10 03:15 UTC by rachelzhang0922

**What this PR does / why we need it**:

**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-01-10 10:21 UTC, saiyan86 requested changes

2023-01-10 10:21 UTC, saiyan86 commented on README-zh.md
> +    谷歌云物联网核心的开源替代
这个直接用英文就行，Google IoT Core的开源替代

2023-01-10 10:21 UTC, saiyan86 commented on README-zh.md
> +Shifu是一个k8s原生的, 生产级的,支持多协议设备接入的，开放的物联网开发平台。
Shifu是一个k8s原生的， 生产级的，支持多协议设备接入的，开放物联网开发平台。

2023-01-10 10:21 UTC, saiyan86 commented on README.md
> +**Open Platform**— avoide vendor lock-in, you can easily deploy Shifu on public, private and hybrid cloud.
**Open Platform**— No vendor lock-in. You can easily deploy Shifu on the edge(from RaspberryPi to edge clusters) or on the cloud(public, private and hybrid cloud are all supported).

2023-01-10 10:21 UTC, saiyan86 commented on README.md
> +# How to connect a private-protocol camera with five lines of code
proprietary-protocol

2023-01-11 02:59 UTC, kris21he commented on README-zh.md
> +This project is distributed under Apache 2.0 License.
translate to chinese?

2023-01-11 03:58 UTC, rachelzhang0922 commented on README-zh.md
> +This project is distributed under Apache 2.0 License.
该项目使用Apache2.0许可证，is that the correct translation?

2023-01-11 10:43 UTC, tomqin93 requested changes
@rachelzhang0922 need to remove submodule

2023-01-11 10:52 UTC, tomqin93 approved these changes

2023-01-11 13:14 UTC, merged