[WIP]Add tdengine to telemetry service
Edgenesis/shifu pull request #459
Opened 2023-01-13 06:40 UTC by geraldkohn

**What this PR does / why we need it**:
add tdengine to telemetry service
**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
The PR includes writing and querying of tdengine data (without binding an http handler). 
The service distinguishes devices by HTTP request headers, 
with the key of the device name being device_name and the key of the event categories being device_tag.

The following are tentatively determined structured data formats:
type StructureData struct {
	DeviceName string    `json:"deviceName"` // device name
	Timestamp  time.Time `json:"timestamp"`  // event time stamp
	Data       string    `json:"data"`       // event content
	Tag        string    `json:"tag"`        // event categories
}
```

2023-01-18 09:24 UTC, tomqin93 requested changes
@geraldkohn please check in the data design for this PR

2023-01-19 01:54 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +		deviceInfo.Name = name[0]
should to check if len(name) > 0?

2023-01-19 01:54 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +		deviceInfo.Tag = tag[0]
check len(tag) > 0

2023-01-19 01:56 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +		logger.Infof("Error to get device name from http header")
if this is an error should use logger.Errorf,
else just logger.Infof("empty device name from http header")

2023-01-19 01:56 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +		logger.Infof("Error to get device tag from http header")
ditto

2023-01-19 01:56 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +		deviceInfo.Name = "default_device_name"
use string const

2023-01-19 01:58 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +		logger.Errorf("Error to query data from tdengine, sql code: %s", querySql)
logger.Errorf("Error to query data from tdengine, sql: %s, error: %s", querySql, err.Error())

2023-01-19 01:59 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +	StructureDatas := make([]*StructureData, 0)
dataRecords := make([]*StructureData, 0)

2023-01-19 02:01 UTC, kris21he commented on pkg/telemetryservice/sql/tdengine/tdengine.go
> +func (db *DBHelper) queryFromDeviceName(devicename string) ([]*StructureData, error) {
actually I don't think we have the requirement of query data from telemetry service, do we?

2023-02-01 01:33 UTC, closed without merging