Update README-zh.md
Edgenesis/shifu pull request #477
Opened 2023-01-29 02:07 UTC by rachelzhang0922

**What this PR does / why we need it**:

**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-01-29 04:55 UTC, saiyan86 submitted a review, later dismissed
LGTM

2023-01-30 11:16 UTC, tomqin93 approved these changes

2023-01-30 11:17 UTC, tomqin93 requested changes
@rachelzhang0922 added 1 comment

2023-01-30 11:17 UTC, tomqin93 commented on README-zh.md
> +[![Discord](https://img.shields.io/badge/WeChat-follow-brightgreen)](https://shifu.run/zh-Hans/subscribe)
Wrong icon?

2023-01-31 08:00 UTC, tomqin93 approved these changes

2023-01-31 08:04 UTC, merged