updata README: capitalization
Edgenesis/shifu pull request #478
Opened 2023-01-29 09:19 UTC by QingZ11

Correct capitalization of some terms, e.g. K8s not k8s. BTW, a post can‘t have more than one first-level title, which will affect crawling and page scoring.

2023-01-29 11:07 UTC, saiyan86 requested changes
@QingZ11 Thanks a lot for the contribution! "BTW, a post can‘t have more than one first-level title, which will affect crawling and page scoring." —— Could you please point me to a link explains this? Thanks!

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## 特点
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## 如何用五行代码连接一个使用私有协议的摄像头
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## 社区
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## 开始上手
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## 贡献
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## Github Star数量
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:07 UTC, saiyan86 commented on README-zh.md
> +## 许可证
这里我们还是保持h1吧，也就是一个#

2023-01-29 11:12 UTC, saiyan86 approved these changes

2023-01-30 01:34 UTC, kris21he approved these changes
LGTM

2023-01-30 02:28 UTC, QingZ11 commented
> @QingZ11 Thanks a lot for the contribution! "BTW, a post can‘t have more than one first-level title, which will affect crawling and page scoring." —— Could you please point me to a link explains this? Thanks!

嘿嘿。。我就不翻译了，直接用中文了。你可以看下这篇文章：[https://ahrefs.com/blog/zh/h1-tag/](https://ahrefs.com/blog/zh/h1-tag/) 简单来说对于一个页面 H1 级的标题是最重要的，相当于你一个内容的重点，但是你如果一篇稿子通篇都是重点就是没有重点了（类比），所以 H1 级别的标题一般是只有一个的，H2 可以有多个。（我不是很精通 SEO，这也是我 SEO 的同事之前教过我的）

在 markdown 中 `#` 生成的标题就是一级标题，我修改了这个 README 中的多个 `#` 改成了 `##`。

2023-01-30 06:01 UTC, saiyan86 commented
> https://ahrefs.com/blog/zh/h1-tag/

感谢！！

2023-01-30 06:09 UTC, QingZ11 commented
> > https://ahrefs.com/blog/zh/h1-tag/
> 
> 感谢！！

顺便问下 😂 我这个小 pr 是有啥问题么？还是说任何一个 pr 都需要 5 个人 ac 了才能 merge（感觉这样有点低效呀

2023-01-30 11:18 UTC, tomqin93 approved these changes
LGTM

2023-01-31 08:04 UTC, merged