fix: Bump github.com/gopcua/opcua from 0.4.0 to 0.5.2
Edgenesis/shifu pull request #735
Opened 2023-10-20 03:49 UTC by cool-wangtongzhou

**What this PR does / why we need it**:

**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [ ] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
```

2023-10-20 06:06 UTC, leepala commented
need to merge after fix sqlserver flaky test

2023-10-22 13:05 UTC, tomqin93 requested changes
@cool-wangtongzhou added some comment, please take a look

2023-10-22 13:05 UTC, tomqin93 commented on examples/httpDeviceShifu/deployment/http-deviceshifu-configmap.yaml
> +
remove empty lines

2023-10-22 13:05 UTC, tomqin93 commented on examples/httpDeviceShifu/deployment/http-edgedevice.yaml
> +
remove empty lines

2023-10-22 13:05 UTC, tomqin93 commented on examples/httpDeviceShifu/deployment/http-deviceshifu-configmap.yaml
> +      moveb:
where are these instructions coming from?

2023-10-22 13:05 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifutcp/etc/edgedevice/config/driverProperties
> +driverImage: edgenesis/mockdevice:v0.0.1
what are these?

2023-10-22 13:05 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifutcp/etc/edgedevice/config/instructions
> +  cmd:
ditto

2023-10-22 13:05 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifutcp/etc/edgedevice/config/telemetries
> +  telemetryUpdateIntervalInMilliseconds: 1000
ditto

2023-10-23 03:33 UTC, cool-wangtongzhou commented
> @cool-wangtongzhou added some comment, please take a look
I have deleted unnecessary things, you can take a look.

2023-10-23 04:35 UTC, tomqin93 approved these changes
LGTM

2023-10-23 05:14 UTC, leepala commented on pkg/deviceshifu/deviceshifuopcua/deviceshifuopcua.go
> +	opcuaClient, err := opcua.NewClient(address, options...)
need to check error

2023-10-24 14:10 UTC, merged