Fix: Bump sigs.k8s.io/controller-runtime from 0.15.1 to 0.16.3
Edgenesis/shifu pull request #736
Opened 2023-10-20 07:27 UTC by cool-wangtongzhou

update-apimachinery-0.28.3

2023-10-22 13:03 UTC, tomqin93 requested changes
@cool-wangtongzhou added some comment, please take a look

2023-10-22 13:03 UTC, tomqin93 commented on pkg/k8s/crd/main.go
> +		// Port:                   9443,
remove if not used

2023-10-22 13:03 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifutcp/etc/edgedevice/config/driverProperties
> +driverImage: edgenesis/mockdevice:v0.0.1
what are these for?

2023-10-22 13:03 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifutcp/etc/edgedevice/config/instructions
> +  cmd:
what are these for?

2023-10-22 13:03 UTC, tomqin93 commented on pkg/deviceshifu/deviceshifutcp/etc/edgedevice/config/telemetries
> +  telemetryUpdateIntervalInMilliseconds: 1000
what are these for?

2023-10-23 03:32 UTC, cool-wangtongzhou commented
> @cool-wangtongzhou added some comment, please take a look
I have deleted unnecessary things, you can take a look.

2023-10-24 14:10 UTC, tomqin93 commented on pkg/k8s/crd/main.go
> +
remove empty line

2023-10-24 14:21 UTC, tomqin93 approved these changes
LGTM

2023-10-24 20:22 UTC, tomqin93 commented
fixed in https://github.com/Edgenesis/shifu/pull/738, closing this PR

2023-10-24 20:22 UTC, closed without merging