Allow Auth with Username and Password for TelemetryService MQTT
Edgenesis/shifu pull request #873
Opened 2024-04-09 10:16 UTC by rhoninl

**What this PR does / why we need it**:
Some MQTT Endpoint need to config username or password to conenct it
**Will this PR make the community happier**? 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**How is this PR tested**
- [ ] unit test
- [x] e2e test
- [x] other (please specify)

**Special notes for your reviewer**:

**Release note**:

```release-note
- update telemetryService MQTT Secret inject Logic
- Add MQTTServerUserName to allow user to Auth with UserName and Password
- Update CRD add MQTTServerUserName to allow user to input Username using plaintext
```

2024-04-09 15:16 UTC, tomqin93 requested changes
Please include document changes as well

2024-04-10 03:31 UTC, rhoninl commented
> Please include document changes as well

https://github.com/Edgenesis/shifu.dev/pull/297

2024-04-10 05:33 UTC, tomqin93 commented on pkg/telemetryservice/mqtt/telemetryservicemqtt.go
> +		setting.MQTTServerSecret = pwd
Let's create a separate `MQTTServerPassword` instead of rewriting itself

2024-04-10 05:40 UTC, rhoninl commented on pkg/deviceshifu/deviceshifumqtt/deviceshifumqtt.go
> +				if mqttProtocolSetting.MQTTSetting != nil && mqttProtocolSetting.MQTTSetting.MQTTServerSecret != "" {
we already have comment here

2024-04-10 07:02 UTC, tomqin93 reviewed
@rhoninl added 1 minor comment, need to add tests for username+password for telemetryservicemqtt

2024-04-10 09:23 UTC, tomqin93 commented on examples/telemetryservice/mqtt/checkoutput_auth.sh
What is this file for?

2024-04-10 09:25 UTC, rhoninl commented on examples/telemetryservice/mqtt/checkoutput_auth.sh
We have two Telemetryservice MQTT tests, one to test pushing data in anonymous mode and the other to test pushing data with authentication. And this file is used for the second one

2024-04-10 09:58 UTC, tomqin93 approved these changes
LGTM

2024-04-10 09:58 UTC, merged